minimal_mistakes_skin: default
locale: en-UK
title: Full Snack Tester
title_separator: '-'
subtitle: null
name: Your Name
description: Homepage for Ben Dowen The Full Snack Tester
url: ''
baseurl: ''
repository: dowenb/fullsnack-home-6388b
teaser: null
logo: null
masthead_title: null
words_per_minute: 200
comments:
  provider: null
  disqus:
    shortname: null
  discourse:
    server: null
  facebook:
    appid: null
    num_posts: null
    colorscheme: null
  utterances:
    theme: null
    issue_term: null
  staticman:
    branch: null
    endpoint: null
reCaptcha:
  siteKey: null
  secret: null
atom_feed:
  path: null
search: null
search_full_content: null
search_provider: null
algolia:
  application_id: null
  index_name: null
  search_only_api_key: null
  powered_by: null
google:
  search_engine_id: null
  instant_search: null
google_site_verification: null
bing_site_verification: null
yandex_site_verification: null
naver_site_verification: null
twitter:
  username: FullSnackTester
facebook:
  username: null
  app_id: null
  publisher: null
og_image: null
social:
  type: null
  name: null
  links: null
analytics:
  provider: false
  google:
    tracking_id: null
    anonymize_ip: null
author:
  name: Ben Dowen
  avatar: null
  bio: I write test code and celebrate the software testing community, every day.
  location: England, UK
  email: ben@dowen.me.uk
  links:
    - label: Email
      icon: fas fa-fw fa-envelope-square
    - label: Website
      icon: fas fa-fw fa-link
    - label: Twitter
      icon: fab fa-fw fa-twitter-square
    - label: GitHub
      icon: fab fa-fw fa-github
footer:
  links:
    - label: Twitter
      icon: fab fa-fw fa-twitter-square
    - label: GitHub
      icon: fab fa-fw fa-github
include:
  - .htaccess
  - _pages
exclude:
  - '*.sublime-project'
  - '*.sublime-workspace'
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test
keep_files:
  - .git
  - .svn
encoding: utf-8
markdown_ext: 'markdown,mkdown,mkdn,mkd,md'
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: |+


incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: 'lsquo,rsquo,ldquo,rdquo'
  enable_coderay: false
sass:
  sass_dir: _sass
  style: compressed
permalink: '/:categories/:title/'
paginate: 5
paginate_path: '/page:num/'
timezone: null
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
compress_html:
  clippings: all
  ignore:
    envs: development
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: null
      share: true
      related: true
